/*
 * DecisionTreePanel.java
 *
 * Created on September 22, 2004, 11:48 AM
 */

package blurock.DecisionTree;
import blurock.coreobjects.BaseDataObject;
import blurock.coreobjects.DataObjectClass;
import blurock.coreobjects.DBaseDataObject;
import javax.swing.JPanel;
import java.io.IOException;
import blurock.DecisionTree.BaseDataDecisionTree;
import blurock.coreobjects.RegisteredClasses;
import blurock.core.ObjectDisplayManager;
import blurock.core.ObjectNotFoundException;
/**
 *
 * @author  reaction
 */
public class DecisionTreeDrawPanel extends javax.swing.JPanel {
    BaseDataDecisionTree DecisionTree;
    DecisionTreeProgramOut programOut;
    
    /** Creates new form DecisionTreePanel */
    public DecisionTreeDrawPanel(BaseDataDecisionTree tree,RegisteredClasses registered) {
        DecisionTree = tree;
        initComponents();
        try {
        ObjectDisplayManager man = new ObjectDisplayManager(registered);
        DataObjectClass treecls = registered.findClass(DecisionTree.Type);
        DBaseDataObject  display = DecisionTree.getDisplayObject(man, treecls);
        JPanel treepanel = display.objectAsPanel();
        programOut = new DecisionTreeProgramOut(tree);
        programOut.treePanel.add(treepanel,java.awt.BorderLayout.CENTER);
        showPanel.add(programOut,java.awt.BorderLayout.CENTER);
        
        } catch(ObjectNotFoundException io) {
            System.out.println("Decision Tree not registered");
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        showPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        showPanel.setLayout(new java.awt.BorderLayout());

        showPanel.setBorder(new javax.swing.border.TitledBorder("Decision Tree"));
        add(showPanel, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel showPanel;
    // End of variables declaration//GEN-END:variables
    
}
