/*
 * DecisionTreeNodeStatsPanel.java
 *
 * Created on September 21, 2004, 8:10 PM
 */

package blurock.DecisionTree;
import javax.swing.JLabel;

/**
 *
 * @author  reaction
 */
public class DecisionTreeNodeStatsPanel extends javax.swing.JPanel {
    
    BaseDataDecisionTreeNodeStats NodeStats = null;
    /** Creates new form DecisionTreeNodeStatsPanel */
    public DecisionTreeNodeStatsPanel(BaseDataDecisionTreeNodeStats stats) {
        NodeStats = stats;
        initComponents();
        for(int i=0;i<NodeStats.predicatePartitionCount;i++) {
            for(int j=0;j < NodeStats.goalPartitionCount;j++) {
                Double d = new Double(NodeStats.PartitionMatrix[i][j]);
                JLabel label = new JLabel(d.toString());
                partitionMatrixPanel.add(label);
            }
        }
        Double dg = new Double(NodeStats.Gain);
        gainValue.setText(dg.toString());
        Double dn = new Double(NodeStats.NumberOfObjects);
        countValue.setText(dn.toString());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        StatisticsPanel = new javax.swing.JPanel();
        simpleStatPanel = new javax.swing.JPanel();
        gainLabel = new javax.swing.JLabel();
        gainValue = new javax.swing.JLabel();
        countLabel = new javax.swing.JLabel();
        countValue = new javax.swing.JLabel();
        partitionMatrixPanel = new javax.swing.JPanel();
        SuperPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        StatisticsPanel.setLayout(new java.awt.GridLayout(2, 1));

        StatisticsPanel.setBorder(new javax.swing.border.TitledBorder("Stats"));
        simpleStatPanel.setLayout(new java.awt.GridLayout(2, 2, 2, 2));

        simpleStatPanel.setBorder(new javax.swing.border.TitledBorder("Gain"));
        gainLabel.setText("Gain");
        simpleStatPanel.add(gainLabel);

        gainValue.setText("0");
        simpleStatPanel.add(gainValue);

        countLabel.setText("Number Of Objects");
        simpleStatPanel.add(countLabel);

        countValue.setText("0");
        simpleStatPanel.add(countValue);

        StatisticsPanel.add(simpleStatPanel);

        partitionMatrixPanel.setLayout(new java.awt.GridLayout(NodeStats.predicatePartitionCount, NodeStats.goalPartitionCount));

        partitionMatrixPanel.setBorder(new javax.swing.border.TitledBorder("Matrix"));
        StatisticsPanel.add(partitionMatrixPanel);

        add(StatisticsPanel, java.awt.BorderLayout.SOUTH);

        SuperPanel.setLayout(new java.awt.BorderLayout());

        SuperPanel.setBorder(new javax.swing.border.TitledBorder("Conjuction"));
        add(SuperPanel, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gainLabel;
    private javax.swing.JPanel partitionMatrixPanel;
    private javax.swing.JLabel countValue;
    private javax.swing.JLabel gainValue;
    private javax.swing.JPanel simpleStatPanel;
    public javax.swing.JPanel SuperPanel;
    private javax.swing.JLabel countLabel;
    private javax.swing.JPanel StatisticsPanel;
    // End of variables declaration//GEN-END:variables
    
}
