/*
 * ConditionPanel.java
 *
 * Created on June 29, 2004, 1:14 AM
 */

package ignition;
import react.utilities.*;
/**
 *
 * @author  reaction
 */
public class ConditionPanel extends javax.swing.JPanel {
     StandardListDialog ParameterNames;
     int ParameterIndex = 0;
    
    /** Creates new form ConditionPanel */
    public ConditionPanel(String[] names) {
        initComponents();
        ParameterNames = new StandardListDialog(names);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        buttonGroup1 = new javax.swing.ButtonGroup();
        Parameter = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();

        setLayout(new java.awt.GridLayout(1, 3));

        Parameter.setText("Parameter");
        Parameter.setToolTipText("Parameter selected to compare");
        Parameter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ParameterMouseClicked(evt);
            }
        });

        add(Parameter);

        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        jRadioButton1.setSelected(true);
        jRadioButton1.setText("GT");
        jPanel1.add(jRadioButton1);

        jRadioButton2.setText("EQ");
        jPanel1.add(jRadioButton2);

        add(jPanel1);

        jTextField1.setText("0.000");
        add(jTextField1);

    }//GEN-END:initComponents

    private void ParameterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ParameterMouseClicked
        ParameterNames.show();
        if(ParameterNames.getReturnStatus() == ParameterNames.RET_OK) {
            String[] names = ParameterNames.listPanel.selectedItemsToString(true);
            Parameter.setText(names[0]);
            /*ParameterIndex = findNameInList(names[0]);*/
            
        }
    }//GEN-LAST:event_ParameterMouseClicked
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton Parameter;
    // End of variables declaration//GEN-END:variables
    
}
