/*
 * AlgorithmOrganization.java
 *
 * Created on July 13, 2001, 7:51 PM
 */

package xml;

/**
 *
 * @author  reaction
 * @version 
 */
public class AlgorithmOrganization extends javax.swing.JPanel {

    /** Creates new form AlgorithmOrganization */
    public AlgorithmOrganization() {
        initComponents ();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        hierarchy2 = new blurock.core.Hierarchy();
        jPanel8 = new javax.swing.JPanel();
        setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints1;
        
        jTabbedPane1.setBorder(new javax.swing.border.TitledBorder(""));
        
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 300));
          jTabbedPane1.addTab("jPanel1", jPanel1);
          
          
        jPanel2.setLayout(new java.awt.GridBagLayout());
          java.awt.GridBagConstraints gridBagConstraints2;
          
          jPanel9.setLayout(new java.awt.GridLayout(1, 2));
            gridBagConstraints2 = new java.awt.GridBagConstraints();
            jPanel2.add(jPanel9, gridBagConstraints2);
            
            
          gridBagConstraints2 = new java.awt.GridBagConstraints();
            jPanel2.add(jPanel10, gridBagConstraints2);
            
            jTabbedPane1.addTab("jPanel2", jPanel2);
          
          
        jPanel3.setLayout(new java.awt.GridBagLayout());
          java.awt.GridBagConstraints gridBagConstraints3;
          
          jPanel5.setLayout(new java.awt.GridLayout(1, 2));
            
            jButton1.setText("jButton1");
              jPanel5.add(jButton1);
              
              
            jButton2.setText("jButton2");
              jPanel5.add(jButton2);
              
              gridBagConstraints3 = new java.awt.GridBagConstraints();
            gridBagConstraints3.gridwidth = 0;
            gridBagConstraints3.fill = java.awt.GridBagConstraints.HORIZONTAL;
            jPanel3.add(jPanel5, gridBagConstraints3);
            
            
          jScrollPane2.setPreferredSize(new java.awt.Dimension(300, 400));
            jScrollPane2.setMinimumSize(new java.awt.Dimension(300, 400));
            
            jScrollPane2.setViewportView(hierarchy2);
              
              gridBagConstraints3 = new java.awt.GridBagConstraints();
            gridBagConstraints3.gridwidth = 0;
            gridBagConstraints3.fill = java.awt.GridBagConstraints.HORIZONTAL;
            jPanel3.add(jScrollPane2, gridBagConstraints3);
            
            jTabbedPane1.addTab("AlgorithmTreePanel", jPanel3);
          
          
        jTabbedPane1.addTab("jPanel8", jPanel8);
          
          
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        add(jTabbedPane1, gridBagConstraints1);
        
    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private blurock.core.Hierarchy hierarchy2;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables

}
