/*
 * FillInModule.java
 *
 * Created on February 21, 2001, 12:53 PM
 */

package xml;
import blurock.core.RunScriptWithOutput;

/**
 *
 * @author  reaction
 * @version 
 */
public class FillInModule extends javax.swing.JPanel {

    XMLOptions xmlOptions;
    /** Creates new form FillInModule */
    public FillInModule(XMLOptions opt) {
        xmlOptions = opt;
        initComponents ();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        packageName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        moduleName = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        setupSetup = new javax.swing.JButton();
        makedefSetup = new javax.swing.JButton();
        includeSetup = new javax.swing.JButton();
        sourceSetup = new javax.swing.JButton();
        exampleRun = new javax.swing.JButton();
        setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints1;
        
        jPanel1.setLayout(new java.awt.GridLayout(2, 2));
        jPanel1.setBorder(new javax.swing.border.TitledBorder("Module Definition"));
        
        jLabel1.setText("Package");
          jLabel1.setToolTipText("The package environment of the module");
          jPanel1.add(jLabel1);
          
          
        packageName.setText("CoreObjects");
          jPanel1.add(packageName);
          
          
        jLabel2.setText("Module");
          jLabel2.setToolTipText("The module to fill");
          jPanel1.add(jLabel2);
          
          
        moduleName.setText("CoreDataObjects");
          jPanel1.add(moduleName);
          
          
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridwidth = 0;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jPanel1, gridBagConstraints1);
        
        
        jPanel2.setLayout(new java.awt.GridLayout(5, 1));
        jPanel2.setBorder(new javax.swing.border.TitledBorder("Generation Operations"));
        
        setupSetup.setToolTipText("Produce the basis 'byhand' source and include");
          setupSetup.setLabel("Module Setup Script");
          setupSetup.setText("Initial 'byhand' Files");
          setupSetup.addMouseListener(new java.awt.event.MouseAdapter() {
              public void mouseClicked(java.awt.event.MouseEvent evt) {
                  setupSetupMouseClicked(evt);
              }
          }
          );
          jPanel2.add(setupSetup);
          
          
        makedefSetup.setToolTipText("Produce the module Makefile");
          makedefSetup.setLabel("Makefile");
          makedefSetup.addMouseListener(new java.awt.event.MouseAdapter() {
              public void mouseClicked(java.awt.event.MouseEvent evt) {
                  makedefSetupMouseClicked(evt);
              }
          }
          );
          jPanel2.add(makedefSetup);
          
          
        includeSetup.setToolTipText("Produce all the include files for all the classes");
          includeSetup.setLabel("Includes");
          includeSetup.setText("Include");
          includeSetup.addMouseListener(new java.awt.event.MouseAdapter() {
              public void mouseClicked(java.awt.event.MouseEvent evt) {
                  includeSetupMouseClicked(evt);
              }
          }
          );
          jPanel2.add(includeSetup);
          
          
        sourceSetup.setToolTipText("Produce all the source files for all the classes");
          sourceSetup.setLabel("Source");
          sourceSetup.addMouseListener(new java.awt.event.MouseAdapter() {
              public void mouseClicked(java.awt.event.MouseEvent evt) {
                  sourceSetupMouseClicked(evt);
              }
          }
          );
          jPanel2.add(sourceSetup);
          
          
        exampleRun.setToolTipText("Generate Basic Test Example");
          exampleRun.setText("Example");
          exampleRun.addMouseListener(new java.awt.event.MouseAdapter() {
              public void mouseClicked(java.awt.event.MouseEvent evt) {
                  exampleRunMouseClicked(evt);
              }
          }
          );
          jPanel2.add(exampleRun);
          
          
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jPanel2, gridBagConstraints1);
        
    }//GEN-END:initComponents

  private void exampleRunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exampleRunMouseClicked
// Add your handling code here:
      String command =  xmlOptions.defaultDirectories.xmlDirectory.getValue() +
                        "/scripts/" + 
                        xmlOptions.standardScripts.exampleSetup.getValue() + " " +
                        packageName.getText() + " " +
                        moduleName.getText() + " " +
                        xmlOptions.defaultDirectories.currentDevDirectory.getValue() + " " +
                        xmlOptions.defaultDirectories.xmlDirectory.getValue();
      RunScriptWithOutput scr = new RunScriptWithOutput(xmlOptions.tLink);
      scr.run(command,true);
  }//GEN-LAST:event_exampleRunMouseClicked

  private void sourceSetupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sourceSetupMouseClicked
// Add your handling code here:
      runProcess("source");
  }//GEN-LAST:event_sourceSetupMouseClicked

  private void includeSetupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_includeSetupMouseClicked
// Add your handling code here:
      runProcess("include");
  }//GEN-LAST:event_includeSetupMouseClicked

  private void makedefSetupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_makedefSetupMouseClicked
// Add your handling code here:
      //runProcess("makedef");
      runProcess("makelib");
  }//GEN-LAST:event_makedefSetupMouseClicked

  private void setupSetupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setupSetupMouseClicked
// Add your handling code here: 
      runProcess("setup");
  }//GEN-LAST:event_setupSetupMouseClicked
  private void runProcess(String name) {
      String command =  xmlOptions.defaultDirectories.xmlDirectory.getValue() +
                        "/scripts/" + 
                        xmlOptions.standardScripts.fillModule.getValue() + " " +
                        packageName.getText() + " " +
                        moduleName.getText() + " " +
                        name + " " +
                        xmlOptions.defaultDirectories.currentDevDirectory.getValue() + " " +
                        xmlOptions.defaultDirectories.xmlDirectory.getValue();
      RunScriptWithOutput scr = new RunScriptWithOutput(xmlOptions.tLink);
      scr.run(command,true);
  }      

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel jPanel1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JTextField packageName;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JTextField moduleName;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JButton setupSetup;
  private javax.swing.JButton makedefSetup;
  private javax.swing.JButton includeSetup;
  private javax.swing.JButton sourceSetup;
  private javax.swing.JButton exampleRun;
  // End of variables declaration//GEN-END:variables

}
