/*
 * ExampleFrame.java
 *
 * Created on February 22, 2001, 8:21 PM
 */

package blurock.core;
import blurock.coreobjects.*;
import blurock.CobwebCluster.*;
import java.io.IOException;
import utilities.ErrorFrame;
import blurock.Consectutive.*;
import javax.swing.JPanel;
import java.awt.BorderLayout;

/**
 *
 * @author  reaction
 * @version 
 */
public class ExampleFrame extends javax.swing.JFrame {

    /** Creates new form ExampleFrame */
    public ExampleFrame() {
        
        initComponents ();
        pack ();
    }

    void SimpleSetReadTest(String inputfile) {
        System.out.println("Simple SetOfObjects Read Test");
        
        RegisteredClasses registered = new RegisteredClasses();
        DataCobwebClusterNodeStatsClass clnode =
                new DataCobwebClusterNodeStatsClass(4030,"CobwebClusterNodeStats",
                "Cobweb Cluster Node Description");
        DataCobwebClusterClass clusterclass = new DataCobwebClusterClass(4031,"CobwebCluster","Cobweb Cluster");
        clusterclass.nodeClass = clnode;
        registered.AddClass(clnode);
        ObjectDisplayManager man = new ObjectDisplayManager(registered);
        
        BaseDataCobwebCluster cluster = new BaseDataCobwebCluster();
        cluster.Name = "CobwebCluster";
        DBaseDataCobwebCluster dcluster = new DBaseDataCobwebCluster(man,cluster,clusterclass);
        RWManager io = new RWManager(registered);
        try {
            io.openInputFile(inputfile);
            cluster.Read(io);
            io.closeInputFile();
        } catch(IOException exp) {
            ErrorFrame fr = new ErrorFrame("Problem with Reading File: \n" + exp.toString());
            fr.show();
        }
        //mainPanel.removeAll();
        CobwebClusterMainPanel panel = new CobwebClusterMainPanel(cluster, clusterclass, man,io);
        //mainPanel.removeAll();
        //mainPanel.add(panel,BorderLayout.CENTER);
        //mainPanel.updateUI();
        jScrollPane1.setViewportView(panel);
        pack ();
    }
    void RegionsTest(String inputfile) {
       System.out.println("Simple Consecutive Read Test");
       ObjectAsTreeNode top = new ObjectAsTreeNode("Top Node");
       RegisteredClasses registered = new RegisteredClasses();
       DataConsecutiveSeriesClass cl1 = new DataConsecutiveSeriesClass(4031,"ConsecutiveSeries",
            "A single node consisting of a consecutive series");
       DataConsecutiveSeriesSetClass setclass = new DataConsecutiveSeriesSetClass(4032,"ConsecutiveSeriesSet",
            "Consecutive Series  Set");
        setclass.nodeClass = cl1;
        registered.AddClass(cl1);
        ObjectDisplayManager man = new ObjectDisplayManager(registered);

        BaseDataConsecutiveSeriesSet set = new BaseDataConsecutiveSeriesSet();
        set.Name = "ConsecutiveSeriesSet";
        DBaseDataConsecutiveSeriesSet dset = new DBaseDataConsecutiveSeriesSet(man,set,setclass);

            RWManager io = new RWManager(registered);
        try {
            io.openInputFile(inputfile);
            io.openOutputFile("/home/reaction/test.out");
            set.Read(io);
            set.Write(io);
            io.closeInputFile();
            io.closeOutputFile();
        } catch(IOException exp) {
            ErrorFrame fr = new ErrorFrame("Problem with Reading File: \n" + exp.toString());
            fr.show();
        }
        ConsectutiveSeriesSetPanel panel = new ConsectutiveSeriesSetPanel(set,setclass,man,io);
       //mainPanel.removeAll();
        //
        //mainPanel.add(panel);
        //getContentPane().add(panel);
        jScrollPane1.setViewportView(panel);
        //mainPanel.updateUI();
        //setVisible(true);
        pack ();
        show();
  }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        titlePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        testButtons = new javax.swing.JPanel();
        fileName = new javax.swing.JTextField();
        consecFileName = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        simple = new javax.swing.JButton();
        readTest = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        titlePanel.setLayout(new java.awt.BorderLayout());

        titlePanel.setBorder(new javax.swing.border.TitledBorder("Example Panel"));
        titlePanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(titlePanel, java.awt.BorderLayout.CENTER);

        testButtons.setLayout(new java.awt.GridLayout(3, 1));

        testButtons.setBorder(new javax.swing.border.TitledBorder("Tests"));
        fileName.setText("clusters.out");
        fileName.setToolTipText("File name to test with");
        testButtons.add(fileName);

        consecFileName.setText("regions.out");
        testButtons.add(consecFileName);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        simple.setText("Read Regions");
        simple.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpleMouseClicked(evt);
            }
        });

        jPanel1.add(simple);

        readTest.setText("Read Clusters");
        readTest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                readTestMouseClicked(evt);
            }
        });

        jPanel1.add(readTest);

        testButtons.add(jPanel1);

        getContentPane().add(testButtons, java.awt.BorderLayout.NORTH);

    }//GEN-END:initComponents

  private void readTestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readTestMouseClicked
// Add your handling code here:
      SimpleSetReadTest(fileName.getText());
  }//GEN-LAST:event_readTestMouseClicked

  private void simpleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpleMouseClicked
// Add your handling code here:
      RegionsTest(consecFileName.getText());
  }//GEN-LAST:event_simpleMouseClicked

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit (0);
    }//GEN-LAST:event_exitForm

    /**
    * @param args the command line arguments
    */
    public static void main (String args[]) {
        new ExampleFrame ().show ();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JPanel testButtons;
    private javax.swing.JButton simple;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField fileName;
    private javax.swing.JTextField consecFileName;
    private javax.swing.JButton readTest;
    // End of variables declaration//GEN-END:variables

}
