/*
 * LogoFrame.java
 *
 * Created on April 21, 2001, 2:56 PM
 */

package blurock.core;

/**
 *
 * @author  reaction
 * @version 
 */
public class LogoFrame extends javax.swing.JFrame {
    
    /** Creates new form LogoFrame */
    public LogoFrame() {
        initComponents ();
        String rootDirectory = "/se/lth/forbrf/terminus/res/images/";
	String textFileName = new String(rootDirectory + "logo.jpg");
        System.out.println("The file: " + textFileName);
        try {
            jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource(textFileName)));
        } catch(NullPointerException ex) {};
        pack ();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jButton1 = new javax.swing.JButton();
        loadProgress = new javax.swing.JProgressBar();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jButton1.setBorderPainted(false);
        jButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jButton1, java.awt.BorderLayout.CENTER);

        getContentPane().add(loadProgress, java.awt.BorderLayout.SOUTH);

    }//GEN-END:initComponents

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit (0);
    }//GEN-LAST:event_exitForm

    /**
    * @param args the command line arguments
    */
    public static void main (String args[]) {
        new LogoFrame ().show ();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    public javax.swing.JProgressBar loadProgress;
    // End of variables declaration//GEN-END:variables

}
