/*
 * TopTreePanel.java
 *
 * Created on February 22, 2001, 8:04 PM
 */

package blurock.core;
import utilities.BaseFrame;
import blurock.core.*;
import blurock.utilities.*;

import java.awt.Dimension;
import javax.swing.*;
import javax.swing.tree.*;
import java.awt.event.*;

/**
 *
 * @author  reaction
 * @version 
 */
public class TopTreePanel extends javax.swing.JPanel {
    ObjectAsTreeNode topNode;
    
            public MouseListener ml = new MouseAdapter() {
            public void mousePressed(MouseEvent e) {
                int selRow = hierarchy.getRowForLocation(e.getX(),e.getY());
                TreePath path = hierarchy.getPathForLocation(e.getX(),e.getY());
                if(path != null) {
                    ObjectAsTreeNode node = (ObjectAsTreeNode) 
                     path.getLastPathComponent();
                    String name = (String) node.getUserObject();
                    if(selRow != -1) {
                        boolean isleaf = hierarchy.getModel().isLeaf(node);
                        if(isleaf) {
                            System.out.println("Is a Leaf Node -->");
                        }
                        BaseScrollFrame fr = new BaseScrollFrame(node.objectAsPanel(),
                                                     name,name,name);
                        fr.pack();
                        fr.show();
                    }
                }
            }
        };

    /** Creates new form TopTreePanel */
    public TopTreePanel(ObjectAsTreeNode topnode) {
        topNode = topnode;
        initComponents ();
        hierarchy.addMouseListener(ml);
        hierarchy.updateUI();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        scrollPanel = new javax.swing.JScrollPane();
        hierarchy = new JTree(topNode);

        setLayout(new java.awt.BorderLayout());

        hierarchy.setPreferredSize(new java.awt.Dimension(600, 800));
        scrollPanel.setViewportView(hierarchy);

        add(scrollPanel, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree hierarchy;
    public javax.swing.JScrollPane scrollPanel;
    // End of variables declaration//GEN-END:variables

}
