/*
 * ChooseParameterPanel.java
 *
 * Created on June 7, 2006, 5:41 PM
 */

package blurock.runignition;

/**
 *
 * @author  reaction
 */
public class ChooseParameterPanel extends javax.swing.JPanel {
    String[] parameters = null;
    public String currentValue = null;
    /** Creates new form ChooseParameterPanel */
    public ChooseParameterPanel() {
        initComponents();
    }
    public ChooseParameterPanel(String[] p) {
        initComponents();
        parameters = p;
        parameterList.setModel(new javax.swing.AbstractListModel() {
            public int getSize() { return parameters.length; }
            public Object getElementAt(int i) { return parameters[i]; }
        });
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        parameterList = new javax.swing.JList();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        parameterList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "H2", "H2O" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        parameterList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        parameterList.setToolTipText("List of possible parameters");
        parameterList.setMaximumSize(new java.awt.Dimension(200, 2000));
        parameterList.setMinimumSize(new java.awt.Dimension(50, 3000));
        parameterList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                parameterListMouseClicked(evt);
            }
        });

        jScrollPane1.setViewportView(parameterList);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);

    }
    // </editor-fold>//GEN-END:initComponents

    private void parameterListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parameterListMouseClicked
        currentValue = (String) parameterList.getSelectedValue();
    }//GEN-LAST:event_parameterListMouseClicked
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList parameterList;
    // End of variables declaration//GEN-END:variables
    
}
