/*
 * PanelDescriptionExpressions.java
 *
 * Created on March 3, 2001, 10:44 PM
 */

package blurock.opandalgs.parameterized;
import javax.swing.*;
/**
 *
 * @author  reaction
 * @version 
 */
public class PanelDescriptionExpressions extends javax.swing.JPanel {

    /** Creates new form PanelDescriptionExpressions */
    public PanelDescriptionExpressions(boolean postopflag, JPanel postop, JPanel desc) {
        initComponents ();
        postOperationFlag.setSelected(postopflag);
        postOperationPanel.add(postop);
        descriptionPanel.add(desc);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        postOperationFlag = new javax.swing.JRadioButton();
        postOperationPanel = new javax.swing.JPanel();
        descriptionPanel = new javax.swing.JPanel();
        setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints1;
        
        
        postOperationFlag.setToolTipText("If enabled, the post operation will be performed");
          postOperationFlag.setText("Post Operation");
          jPanel1.add(postOperationFlag);
          
          
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridwidth = 0;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jPanel1, gridBagConstraints1);
        
        
        postOperationPanel.setBorder(new javax.swing.border.TitledBorder("Post Operation (if enabled)"));
        postOperationPanel.setToolTipText("Post Operation");
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridwidth = 0;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(postOperationPanel, gridBagConstraints1);
        
        
        descriptionPanel.setBorder(new javax.swing.border.TitledBorder("Description"));
        descriptionPanel.setToolTipText("The description");
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridwidth = 0;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(descriptionPanel, gridBagConstraints1);
        
    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton postOperationFlag;
    private javax.swing.JPanel postOperationPanel;
    private javax.swing.JPanel descriptionPanel;
    // End of variables declaration//GEN-END:variables

}
