/*
 * ClusterParameters.java
 *
 * Created on December 10, 2003, 11:50 AM
 */

package react.menu;

/**
 *
 * @author  reaction
 */
public class ClusterParameters extends javax.swing.JPanel {
    
    /** Creates new form ClusterParameters */
    public ClusterParameters() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        dataFileField = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        jPanel21 = new javax.swing.JPanel();
        dataFileField1 = new javax.swing.JTextField();
        browseButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Read = new javax.swing.JButton();
        Instances = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBorder(new javax.swing.border.TitledBorder("Set Up Data"));
        dataFileField.setText("SpeciesData.txt");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(dataFileField, gridBagConstraints);

        browseButton.setText("Browse");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(browseButton, gridBagConstraints);

        jPanel21.setLayout(new java.awt.GridBagLayout());

        jPanel21.setBorder(new javax.swing.border.TitledBorder("Set Up Data"));
        dataFileField1.setText("SpeciesData.txt");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        jPanel21.add(dataFileField1, gridBagConstraints);

        browseButton1.setText("Browse");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        jPanel21.add(browseButton1, gridBagConstraints);

        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        Read.setText("Read");
        jPanel3.add(Read);

        Instances.setText("Instances");
        jPanel3.add(Instances);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        jPanel21.add(jPanel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(jPanel21, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jPanel2, gridBagConstraints);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dataFileField;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField dataFileField1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton browseButton;
    private javax.swing.JButton Instances;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JButton browseButton1;
    private javax.swing.JButton Read;
    // End of variables declaration//GEN-END:variables
    
}
