/*
 * MoleculeMenu.java
 *
 * Created on January 21, 2001, 10:36 AM
 */

package react.menu;
import react.common.*;
import react.utilities.*;
import java.awt.Dimension;

/**
 *
 * @author  reaction
 * @version 
 */
public class MoleculeMenu extends javax.swing.JPanel {

    /** Creates new form MoleculeMenu */
    public MoleculeMenu() {
        initComponents ();
        moleculePanel.add(moleculeList.getObjectPanel());
        moleculePanel.updateUI();
    }
    public MoleculeMenu(TopReactionMenu top,Dimension psize) {
        initComponents ();
        //setup(top,psize);
        moleculePanel.add(moleculeList.getObjectPanel());
        moleculePanel.updateUI();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        moleculeList = new react.molecules.MoleculeListButton();
        adjust = new javax.swing.JButton();
        moleculePanel = new javax.swing.JPanel();
        setLayout(new java.awt.BorderLayout());
        setBackground(java.awt.Color.white);
        
        jPanel1.setLayout(new java.awt.GridLayout(1, 2));
        jPanel1.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
        jPanel1.setBackground(java.awt.Color.white);
        
        moleculeList.setBackground(java.awt.Color.white);
          jPanel1.add(moleculeList);
          
          
        adjust.setBorder(new javax.swing.border.BevelBorder(0));
          adjust.setText("Adjust");
          adjust.setBackground(java.awt.Color.white);
          adjust.addMouseListener(new java.awt.event.MouseAdapter() {
              public void mousePressed(java.awt.event.MouseEvent evt) {
                  adjustMousePressed(evt);
              }
          }
          );
          jPanel1.add(adjust);
          
          
        add(jPanel1, java.awt.BorderLayout.NORTH);
        
        
        moleculePanel.setPreferredSize(new java.awt.Dimension(400, 400));
        moleculePanel.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
        moleculePanel.setBackground(java.awt.Color.lightGray);
        moleculePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moleculePanelMousePressed(evt);
            }
        }
        );
        
        add(moleculePanel, java.awt.BorderLayout.CENTER);
        
    }//GEN-END:initComponents

  private void moleculePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moleculePanelMousePressed
// Add your handling code here:
      moleculeList.drawMolecule.relax();
  }//GEN-LAST:event_moleculePanelMousePressed

  private void adjustMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adjustMousePressed
// Add your handling code here:
      moleculeList.drawMolecule.relax();
  }//GEN-LAST:event_adjustMousePressed

    public void setup(TopReactionMenu top,Dimension psize) {
        moleculeList.setup(new String("Molecule"),
                top.Common.MoleculeList,
                top,
                psize);
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    public react.molecules.MoleculeListButton moleculeList;
    private javax.swing.JButton adjust;
    private javax.swing.JPanel moleculePanel;
    // End of variables declaration//GEN-END:variables

}
