/*
 * BaseScrollFrame.java
 *
 * Created on March 1, 2001, 2:12 PM
 */

package blurock.utilities;
import javax.swing.*;
import java.awt.Dimension;
import blurock.utilities.*;

/**
 *
 * @author  reaction
 * @version 
 */
public class BaseScrollFrame extends javax.swing.JFrame {
    public String frameName;
    
    public String textExplanation;
    
    public String oneLineExplanation;

    /** Creates new form BaseScrollFrame */
    public BaseScrollFrame(JPanel panel,
                        String name,
                        String tabtitle,
                        String text) {
        frameName = name;
        oneLineExplanation = tabtitle;
        textExplanation = text;
        initComponents ();
        mainPanel.add(panel);
        pack ();
    }
    public BaseScrollFrame() {
        frameName = "Default";
        oneLineExplanation = "";
        textExplanation = "";
        initComponents ();
        pack ();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jScrollPane1 = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();
        dismissButton = new javax.swing.JButton();
        setName(frameName);
        setTitle(frameName);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        }
        );
        
        jScrollPane1.setPreferredSize(new java.awt.Dimension(500, 400));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(410, 50));
        
        mainPanel.setToolTipText(oneLineExplanation);
          jScrollPane1.setViewportView(mainPanel);
          
          
        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);
        
        
        dismissButton.setToolTipText("Close Window");
        dismissButton.setText("Dismiss");
        dismissButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dismissButtonMouseClicked(evt);
            }
        }
        );
        
        getContentPane().add(dismissButton, java.awt.BorderLayout.SOUTH);
        
    }//GEN-END:initComponents

  private void dismissButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dismissButtonMouseClicked
// Add your handling code here:
        setVisible (false);
        dispose ();
  }//GEN-LAST:event_dismissButtonMouseClicked

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit (0);
    }//GEN-LAST:event_exitForm

    /**
    * @param args the command line arguments
    */
    public static void main (String args[]) {
        new BaseScrollFrame ().show ();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton dismissButton;
    // End of variables declaration//GEN-END:variables

}
