/*
 * PanelExpressionTree.java
 *
 * Created on February 28, 2001, 4:39 PM
 */

package blurock.utilities;
import javax.swing.*;
import utilities.BaseFrame;
/**
 *
 * @author  reaction
 * @version 
 */
public class TopObjectPanel extends javax.swing.JPanel {
    JPanel topInfo;
    String className;

    /** Creates new form PanelExpressionTree */
    public TopObjectPanel(String name,JPanel top,JPanel mpanel) {
        initComponents ();
        topInfo = top;
        className = name;
        nameButton.setText(name);
        mainPanel.add(mpanel);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        nameButton = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints1;
        
        nameButton.setText("jButton1");
        nameButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameButtonMouseClicked(evt);
            }
        }
        );
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridwidth = 0;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(nameButton, gridBagConstraints1);
        
        
        mainPanel.setToolTipText("Press for Basic Object Information");
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridwidth = 0;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(mainPanel, gridBagConstraints1);
        
    }//GEN-END:initComponents

  private void nameButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameButtonMouseClicked
// Add your handling code here:
      BaseFrame f = new BaseFrame(topInfo,className,"Class Info","");
      f.show();

  }//GEN-LAST:event_nameButtonMouseClicked


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton nameButton;
  private javax.swing.JPanel mainPanel;
  // End of variables declaration//GEN-END:variables

}
