/*
 * StandardLIstPanel.java
 *
 * Created on January 18, 2001, 10:22 PM
 */


package react.utilities;
import java.awt.Dimension;

/**
 *
 * @author Edward S. Blurock
 * @version 2000
 */
public class StandardListPanel extends javax.swing.JPanel {

    /** Creates new form StandardLIstPanel */
    public StandardListPanel() {
        panelTitle = new String("List");
        
       listModel = new StandardListListModel();
        initComponents ();
        //jList2.setListData(names);
    }

/** The standard constructor
 * @param title <I>The title of the panel</I>
 * @param names <I>The set of names to be in the list</I>
 */    
    public StandardListPanel(java.lang.String title,java.lang.String[] names) {
        panelTitle = title;
       listModel = new StandardListListModel(names);
        initComponents ();
       // jList2.setListData(names);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jScrollPane1 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();

        setLayout(new java.awt.BorderLayout());

        setName(panelTitle);
        jScrollPane1.setBackground(new java.awt.Color(153, 255, 255));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(300, 50));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(400, 400));
        jList2.setBackground(new java.awt.Color(204, 204, 255));
        jList2.setModel(listModel);
        jScrollPane1.setViewportView(jList2);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents

/** Create a new list of names from the selected names
 * @return The list of names is returned
 * @param selectAllIfEmpty <I>If true and no selection has been made,
 * then select all the elements</I>
 */    
    public String[] selectedItemsToString(boolean selectAllIfEmpty) {
        int[] indices = jList2.getSelectedIndices();
	if(indices.length == 0)
	{
	    selectAllElements();
	    indices = jList2.getSelectedIndices();
	}
	String[] names = new String[indices.length];
	for(int i=0;i<indices.length;i++) {
		names[i] = (String) jList2.getModel().getElementAt(indices[i]);
	    }
	return names;

    }    

/** Set all the elements to be selected
 */    
    public void selectAllElements() {
	int[] indices = new int[jList2.getModel().getSize()];
	for(int i=0;i<jList2.getModel().getSize();i++)  {
		indices[i] = i;
	    }
	jList2.setSelectedIndices(indices);
    }
    public String[] getData() {
        selectAllElements();
        return selectedItemsToString(false);
    }
        
/** Initialize list with <B>names</B>
 * @param names <I>The new list of names</I>
 */    
    public void setData(java.lang.String[] names) {
        String snames[] = new String[names.length];
        for(int i=0;i<names.length;i++) {
            snames[i]= names[i];
            System.out.println(">" + snames[i] + "<");
        }
        System.out.println(panelTitle);
        System.out.println(names.length);
        
        java.util.Arrays.sort(snames);
        listModel = new StandardListListModel(snames);
        jList2.setModel(listModel);
    }
    public void setPreferedSize(java.awt.Dimension d) {
        System.out.println("List preferredSize" + d);
        //super.setPreferredSize(d);
        //jScrollPane1.setPreferredSize(new Dimension(d.width-20,d.height-20));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

/** The title of the panel (shown at the top)
 */    
    public String panelTitle;
    
    private StandardListListModel listModel;
    
}
