/*
 * ExactlyEqualPredicatePanel.java
 *
 * Created on July 12, 2005, 4:32 PM
 */

package blurock.logic.predicates;
import blurock.core.ObjectNotFoundException;
import blurock.core.ObjectAsTreeNode;
import blurock.core.ObjectDisplayManager;
import blurock.coreobjects.BaseDataObject;
import blurock.coreobjects.DataObjectClass;
import blurock.coreobjects.DBaseDataObject;
import javax.swing.JPanel;
import java.awt.BorderLayout;
import blurock.opandalgs.ops.DataOperationClass;
import blurock.opandalgs.ops.BaseDataOperation;
import blurock.opandalgs.ops.DBaseDataOperation;
import blurock.core.ObjectDisplayManager;
/**
 *
 * @author  reaction
 */
public class ExactlyEqualPredicatePanel extends javax.swing.JPanel {
    BaseDataExactlyEqualPredicate predicate = null;
    /** Creates new form ExactlyEqualPredicatePanel */
    public ExactlyEqualPredicatePanel() {
        initComponents();
    }
     public ExactlyEqualPredicatePanel(ObjectDisplayManager man, 
                                       BaseDataExactlyEqualPredicate pred,
                                       DataExactlyEqualPredicateClass objcls) {
         predicate = pred;
        initComponents();
        parameterField.setText(predicate.parameterName);
        DBaseDataObject dobj = predicate.objectToCompare.getDisplayObject(man,objcls.objectClass);
        JPanel objpanel = dobj.objectAsPanel();
        objpanel.add(objpanel,java.awt.BorderLayout.CENTER);
        logicTypeField.setText(pred.logicClass.Name);
    }
   
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        parameterField = new javax.swing.JTextField();
        objectScoll = new javax.swing.JScrollPane();
        objectPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        logicTypeLabel = new javax.swing.JLabel();
        logicTypeField = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        parameterField.setText("ParameterName");
        add(parameterField, java.awt.BorderLayout.NORTH);

        objectPanel.setLayout(new java.awt.BorderLayout());

        objectScoll.setViewportView(objectPanel);

        add(objectScoll, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        logicTypeLabel.setText("Logic Type");
        jPanel1.add(logicTypeLabel);

        logicTypeField.setText("logicType");
        jPanel1.add(logicTypeField);

        add(jPanel1, java.awt.BorderLayout.SOUTH);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField logicTypeField;
    private javax.swing.JLabel logicTypeLabel;
    private javax.swing.JPanel objectPanel;
    private javax.swing.JScrollPane objectScoll;
    private javax.swing.JTextField parameterField;
    // End of variables declaration//GEN-END:variables
    
}
