/*
 * ErrorDialog.java
 *
 * Created on March 1, 2004, 12:15 PM
 */

package blurock.reaction.GUI;

/**
 *
 * @author  moliate
 */
public class ErrorDialog extends javax.swing.JDialog {
    
    /** Creates new form ErrorDialog */
    public ErrorDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {
        mainPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        message = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        Dismiss = new javax.swing.JButton();

        setTitle("Error");
        setModal(true);
        setName("Error dialog");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        mainPanel.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/se/lth/forbrf/terminus/res/images/metal-Error.gif")));
        jLabel1.setText("  error   ");
        jPanel3.add(jLabel1, java.awt.BorderLayout.WEST);

        message.setBackground((java.awt.Color) javax.swing.UIManager.getDefaults().get("Button.background"));
        message.setEditable(false);
        message.setLineWrap(true);
        message.setWrapStyleWord(true);
        message.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        message.setMinimumSize(new java.awt.Dimension(250, 100));
        message.setPreferredSize(new java.awt.Dimension(250, 100));
        jPanel3.add(message, java.awt.BorderLayout.CENTER);

        mainPanel.add(jPanel3, java.awt.BorderLayout.CENTER);

        Dismiss.setMnemonic('d');
        Dismiss.setText(" Dismiss ");
        Dismiss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DismissActionPerformed(evt);
            }
        });

        jPanel1.add(Dismiss);

        mainPanel.add(jPanel1, java.awt.BorderLayout.SOUTH);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }

    private void DismissActionPerformed(java.awt.event.ActionEvent evt) {
        closeDialog(null);
    }
    
    private void DetailsActionPerformed(java.awt.event.ActionEvent evt)
    {
        if (null == Details.getSelectedObjects() )
        {
            getContentPane().remove(mainPanel);
            getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);
            getContentPane().remove(stacktraceScroller);
            Details.setText("Details >>");
            pack();
            repaint();
        }
        else
        {
            getContentPane().remove(mainPanel);
            getContentPane().add(mainPanel, java.awt.BorderLayout.NORTH);
            getContentPane().add(stacktraceScroller, java.awt.BorderLayout.CENTER);
            Details.setText("Details <<");
            pack();
            repaint();
        }
            
    }
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {
        setVisible(false);
        dispose();
    }
    
    public void setMessage(String m)
    {
        message.setText(m);
        pack();
        repaint();
    }
    
    public void setDetails(String d)
    {
        
        stacktrace = new javax.swing.JTextArea();
        stacktrace.setLineWrap(false);
        //stacktrace.setMinimumSize(new java.awt.Dimension(200, 100));

        stacktrace.setText(d);
        stacktraceScroller = new javax.swing.JScrollPane(stacktrace);
        stacktraceScroller.setPreferredSize(new java.awt.Dimension(200, 100));
        
        Details = new javax.swing.JToggleButton();
        Details.setFont(new java.awt.Font("Dialog", 0, 12));
        Details.setText("Details >>");
        Details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetailsActionPerformed(evt);
            }
        });
        jPanel1.add(Details);
        pack();
        repaint();
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new ErrorDialog(new javax.swing.JFrame(), true).setVisible(true);
    }
    
    private javax.swing.JToggleButton Details;    
    private javax.swing.JTextArea stacktrace;  
    private javax.swing.JScrollPane stacktraceScroller;
    // Variables declaration - do not modify
    private javax.swing.JButton Dismiss;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextArea message;
    // End of variables declaration
    
}
