/*
 * DescriptionPointPanel.java
 *
 * Created on October 14, 2003, 9:13 PM
 */

package blurock.CobwebCluster;

/**
 *
 * @author  reaction
 */
public class DescriptionPointPanel extends javax.swing.JPanel {
    
    public BaseDataCobwebClusterDescriptorPoint point;
    int intValue = 0;
    
    /** Creates new form DescriptionPointPanel */
    public DescriptionPointPanel() {
        point = new BaseDataCobwebClusterDescriptorPoint();
        initComponents();
    }
    public DescriptionPointPanel(BaseDataCobwebClusterDescriptorPoint pnt) {
        point = pnt;
        float f = (float) Math.abs(100.0*point.differenceValue);
        intValue = Math.round(f);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setLayout(new java.awt.GridLayout(1, 2));

        jPanel1.setLayout(new java.awt.GridLayout(1, 3));

        jPanel1.setMaximumSize(new java.awt.Dimension(500, 20));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 20));
        jLabel1.setText(point.parameterDescription);
        jPanel1.add(jLabel1);

        jLabel2.setText(String.valueOf(point.differenceValue));
        jPanel1.add(jLabel2);

        jLabel3.setText(String.valueOf(point.descriptorValue));
        jPanel1.add(jLabel3);

        add(jPanel1);

        jProgressBar1.setValue(intValue);
        add(jProgressBar1);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
    
}
