/*
 * ConsectutiveSeriesSetPanel.java
 *
 * Created on November 10, 2003, 3:44 PM
 */

package blurock.Consectutive;
import utilities.*;
import blurock.core.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.awt.*;

/**
 *
 * @author  reaction
 */
public class ConsectutiveSeriesSetPanel extends javax.swing.JPanel {
    BaseDataConsecutiveSeriesSet seriesSet;
    DataConsecutiveSeriesSetClass seriesSetClass;
    FileFrame fileFrame = new FileFrame("Cluster Series Information",".","out");
    RWManager io;
    DBaseDataConsecutiveSeriesSet dset;
   
    /** Creates new form ConsectutiveSeriesSetPanel */
    public ConsectutiveSeriesSetPanel() {
        initComponents();
    }
     public ConsectutiveSeriesSetPanel(BaseDataConsecutiveSeriesSet set,
                                      DataConsecutiveSeriesSetClass setclass,
                                      ObjectDisplayManager man, 
                                      RWManager rw) {
        seriesSet = set;
        seriesSetClass = setclass;
        io = rw;
        
        dset = new DBaseDataConsecutiveSeriesSet(man,seriesSet,seriesSetClass);
        ObjectAsTreeNode top = new ObjectAsTreeNode(seriesSet.Name);
        dset.objectAsSubTree(top);
        TopTreePanel tree = new TopTreePanel(top);
        tree.scrollPanel.setPreferredSize(new java.awt.Dimension(500, 400));
        tree.scrollPanel.setMinimumSize(new java.awt.Dimension(500, 400));
        
       initComponents();
       treePanel.add(tree);
     }
   
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        buttonsPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        seriesWrite = new javax.swing.JButton();
        regionButton = new javax.swing.JButton();
        divisionsButton = new javax.swing.JButton();
        treePanel = new javax.swing.JPanel();

        setLayout(new java.awt.GridBagLayout());

        setAutoscrolls(true);
        buttonsPanel.setLayout(new java.awt.GridLayout(1, 1));

        buttonsPanel.setPreferredSize(new java.awt.Dimension(500, 35));
        jPanel1.setLayout(new java.awt.GridLayout(1, 3));

        seriesWrite.setText("Write");
        seriesWrite.setToolTipText("write out series information");
        seriesWrite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seriesWriteMouseClicked(evt);
            }
        });

        jPanel1.add(seriesWrite);

        regionButton.setText("Draw Regions");
        regionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regionButtonMouseClicked(evt);
            }
        });

        jPanel1.add(regionButton);

        divisionsButton.setText("Divisions");
        divisionsButton.setToolTipText("Compute and print out the divisions");
        divisionsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                divisionsButtonMouseClicked(evt);
            }
        });

        jPanel1.add(divisionsButton);

        buttonsPanel.add(jPanel1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(buttonsPanel, gridBagConstraints);

        treePanel.setLayout(new java.awt.GridLayout(1, 1));

        treePanel.setBorder(new javax.swing.border.TitledBorder("Region Levels"));
        treePanel.setMinimumSize(new java.awt.Dimension(500, 200));
        treePanel.setPreferredSize(new java.awt.Dimension(500, 400));
        treePanel.setAutoscrolls(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(treePanel, gridBagConstraints);

    }//GEN-END:initComponents

    private void divisionsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divisionsButtonMouseClicked
        seriesSet.findLevelRegions();
        String out = seriesSet.LevelsToString();
        OutputFrame fr = new OutputFrame(out);
        fr.show();
    }//GEN-LAST:event_divisionsButtonMouseClicked

    private void regionButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regionButtonMouseClicked
        dset.display();
    }//GEN-LAST:event_regionButtonMouseClicked

    private void seriesWriteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seriesWriteMouseClicked
      fileFrame.getFile();
       File f = fileFrame.chosenFile;
       try {
            io.openOutputFile(f.getAbsolutePath());
       } catch(FileNotFoundException ex) {
            ErrorFrame fr = new ErrorFrame("Problem with writing File: \n" + f.toString());
            fr.show();
       }
       try {
            seriesSet.Write(io);
            io.closeOutputFile();
       } catch(IOException ex) {
            ErrorFrame fr = new ErrorFrame("Problem with writing File: \n" + f.toString());
            fr.show();
       }

    }//GEN-LAST:event_seriesWriteMouseClicked
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton regionButton;
    private javax.swing.JPanel treePanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton divisionsButton;
    private javax.swing.JButton seriesWrite;
    // End of variables declaration//GEN-END:variables
    
}
