/*
 * PanelPopulation.java
 *
 * Created on March 2, 2001, 12:33 PM
 */

package blurock.pop.base;
import javax.swing.JPanel;
/**
 *
 * @author  reaction
 * @version 
 */
public class PanelPopulation extends javax.swing.JPanel {

    /** Creates new form PanelPopulation */
    public PanelPopulation(int popsize, JPanel genobj) {
        initComponents ();
        populationSize.setText(String.valueOf(popsize));
        geneticObjectPanel.add(genobj);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        populationSizeButton = new javax.swing.JButton();
        populationSize = new javax.swing.JTextField();
        geneticObjectPanel = new javax.swing.JPanel();
        setLayout(new java.awt.BorderLayout());
        
        jPanel1.setBorder(new javax.swing.border.TitledBorder("Population"));
        
        jPanel2.setLayout(new java.awt.GridLayout(1, 2));
          
          populationSizeButton.setToolTipText("The number of genetic objects in the population");
            populationSizeButton.setText("PopulationSize");
            jPanel2.add(populationSizeButton);
            
            
          populationSize.setText("0");
            jPanel2.add(populationSize);
            
            jPanel1.add(jPanel2);
          
          
        jPanel1.add(geneticObjectPanel);
          
          
        add(jPanel1, java.awt.BorderLayout.CENTER);
        
    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton populationSizeButton;
    public javax.swing.JTextField populationSize;
    public javax.swing.JPanel geneticObjectPanel;
    // End of variables declaration//GEN-END:variables

}
