/*
 * InformationPanel.java
 *
 * Created on January 31, 2001, 5:35 AM
 */

package utilities;
import react.common.*;
import java.io.*;
import java.net.*;


/**
 *
 * @author  reaction
 * @version 
 */
public class InformationPanel extends javax.swing.JPanel {

    public String panelName = "Description";
    private String rootDirectory;
    
    /** Creates new form InformationPanel */
    public InformationPanel() {
        initComponents ();
    }
    public void setup(String rootdir) {
        rootDirectory = rootdir;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        descriptionText = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        setBorder(new javax.swing.border.TitledBorder("Description"));
        add(descriptionText, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents

    public void setInformationFromFile(String name) {
	if(currentInformation == null ||
	   currentInformation != name) {
	    String textFileName = new String(rootDirectory + name);
	    String text = contentsOfFile(textFileName);
	    descriptionText.setText(text);
	}
    }

    public static String contentsOfFile(String filename) {
	String s = new String();
	File f;
	char[] buff = new char[50000];
	InputStream is;
	InputStreamReader reader;
        try {
	    f = new File(filename);
	    reader = new FileReader(f);
	    int nch;
	    while ((nch = reader.read(buff, 0, buff.length)) != -1) {
		s = s + new String(buff, 0, nch);
	    }
	} catch (java.io.IOException ex) {
	    s = "Could not load file: " + filename;
	}
	return s;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea descriptionText;
    // End of variables declaration//GEN-END:variables

    public String currentInformation;    

    public TopReactionMenu Top;
    
}
