/*
 * ManageListOfMolecules.java
 *
 * Created on February 1, 2001, 3:39 PM
 */

package react.molecules;
import react.common.*;
import react.utilities.*;


/**
 *
 * @author  reaction
 * @version 
 */
public class ManageListOfMolecules extends javax.swing.JPanel {

    /** Creates new form ManageListOfMolecules */
    public ManageListOfMolecules() {
        reactList = new ReactList();
        Title = new String("MoleculeList");
        maxSize = 10;
        initComponents ();
    }
    public ManageListOfMolecules(TopReactionMenu top, String title, int max) {
        Top = top;
        Title = title;
        maxSize = max;
        reactList = Top.Common.MoleculeList;
        initComponents ();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        moleculeList = new ManageListItems(Top,Title,reactList,maxSize);
        
        setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints1;
        
        java.awt.GridBagConstraints gridBagConstraints2;
        moleculeList.setBorder(new javax.swing.border.TitledBorder("List of Molecules"));
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridwidth = 0;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        add(moleculeList, gridBagConstraints1);
        
    }//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public react.utilities.ManageListItems moleculeList;
    // End of variables declaration//GEN-END:variables

    public TopReactionMenu Top;    

    public String Title;
    
    public int maxSize;
    
    public ReactList reactList;
    
}
