/*
 * SystemAlgorithms.java
 *
 * Created on February 18, 2001, 9:08 AM
 */

package blurock.common;
import react.common.*;


/**
 *
 * @author  reaction
 * @version 
 */
public class SystemAlgorithms extends javax.swing.JPanel {

    /** Creates new form SystemAlgorithms */
    public SystemAlgorithms() {
        initComponents ();
        instanceSetup.setValueName("InstanceSetUpAlg");
        instanceSetup.setDefaultValue("InstanceSetUpAlg");
        expressionCalc.setDefaultValue("Expression");
        expressionCalc.setValueName("Evaluate an Expression");
        dataBaseMove.setDefaultValue("MoveIt");
        dataBaseMove.setValueName("Move To and From the database");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jTabbedPane1 = new javax.swing.JTabbedPane();
        InstAttr = new javax.swing.JPanel();
        instanceSetup = new react.common.StandardName();
        standardName2 = new react.common.StandardName();
        Util = new javax.swing.JPanel();
        expressionCalc = new react.common.StandardName();
        dataBaseMove = new react.common.StandardName();
        setLayout(new java.awt.BorderLayout());
        
        
        InstAttr.setLayout(new java.awt.GridLayout(5, 1));
          
          instanceSetup.setLayout(new java.awt.GridLayout(2, 3));
            instanceSetup.setName("InstanceSetUpAlg");
            instanceSetup.setToolTipText("Algorithm to set up test and training sets");
            InstAttr.add(instanceSetup);
            
            
          standardName2.setLayout(new java.awt.GridLayout(2, 3));
            InstAttr.add(standardName2);
            
            jTabbedPane1.addTab("InstAttr", null, InstAttr, "Algorithms for the Instance, Attribute and Class Examine and setup");
          
          
        Util.setLayout(new java.awt.GridLayout(5, 1));
          
          expressionCalc.setLayout(new java.awt.GridLayout(2, 3));
            Util.add(expressionCalc);
            
            
          dataBaseMove.setLayout(new java.awt.GridLayout(2, 3));
            Util.add(dataBaseMove);
            
            jTabbedPane1.addTab("jPanel2", null, Util, "Utilities");
          
          
        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
        
    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel InstAttr;
    public react.common.StandardName instanceSetup;
    public react.common.StandardName standardName2;
    private javax.swing.JPanel Util;
    public react.common.StandardName expressionCalc;
    public react.common.StandardName dataBaseMove;
    // End of variables declaration//GEN-END:variables

}
