/*
 * BuildMechanism.java
 *
 * Created on April 1, 2002, 8:57 PM
 */

package react.mechanisms;
import react.common.TopReactionMenu;
import blurock.instattr.GetAttributeParameter;
import blurock.coreobjects.BaseDataKeyWords;
import utilities.ErrorFrame;
import blurock.utilities.SetUpClassAttrFile;
import blurock.core.RunAlgorithm;
import blurock.core.RunCommand;
import blurock.utilities.SetUpClassAttrFile;

/**
 *
 * @author  reaction
 * @version 
 */
public class BuildMechanism extends javax.swing.JPanel {
TopReactionMenu Top;
    /** Creates new form BuildMechanism */
    public BuildMechanism(TopReactionMenu top) {
            Top = top;
        initComponents ();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        moleculeListButton = new javax.swing.JButton();
        moleculeListField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        reactionListButton = new javax.swing.JButton();
        reactionListField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        mechanismNameField = new javax.swing.JTextField();
        buildMechanism = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(3, 1));

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        jPanel1.setBorder(new javax.swing.border.TitledBorder("MoleculeList"));
        moleculeListButton.setText("Molecule List");
        jPanel1.add(moleculeListButton);

        moleculeListField.setText("MoleculeList");
        jPanel1.add(moleculeListField);

        add(jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        jPanel2.setBorder(new javax.swing.border.TitledBorder("Reaction List"));
        reactionListButton.setText("Reaction List");
        jPanel2.add(reactionListButton);

        reactionListField.setText("ReactionList");
        jPanel2.add(reactionListField);

        add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        jPanel3.setBorder(new javax.swing.border.TitledBorder("Mechanism"));
        mechanismNameField.setText("NewMechanism");
        jPanel3.add(mechanismNameField);

        buildMechanism.setText("Build");
        buildMechanism.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buildMechanismMouseClicked(evt);
            }
        });

        jPanel3.add(buildMechanism);

        add(jPanel3);

    }
    // </editor-fold>//GEN-END:initComponents

  private void buildMechanismMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buildMechanismMouseClicked
    SetUpClassAttrFile inpfile = new SetUpClassAttrFile(Top,"BuildMechanism",
                "Build Mechanism From Lists");
    inpfile.printString("Mechanism",mechanismNameField.getText());
    
    inpfile.read(false);
    
    if(!moleculeListField.getText().equals("MoleculeList")) {
        String transS1 = "TransferAttributes " + 
                       moleculeListField.getText() + " MoleculeList";
        RunCommand runit0 = new RunCommand(Top,transS1,false);
    }
    if(!moleculeListField.getText().equals("ReactionList")) {    
        String transS2 = "TransferAttributes " +
                       reactionListField.getText() + " ReactionList";
        RunCommand runit1 = new RunCommand(Top,transS2,false);
    }
    RunAlgorithm runit2 = new RunAlgorithm(Top,"BuildMechanism",false);
    runit2.run();
    runit2.showResults();
  }//GEN-LAST:event_buildMechanismMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buildMechanism;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField mechanismNameField;
    private javax.swing.JButton moleculeListButton;
    private javax.swing.JTextField moleculeListField;
    private javax.swing.JButton reactionListButton;
    private javax.swing.JTextField reactionListField;
    // End of variables declaration//GEN-END:variables

}
