/*
 * MechanismListButton.java
 *
 * Created on January 22, 2001, 1:16 PM
 */

package react.mechanisms;

/**
 *
 * @author  reaction
 * @version 
 */
public class MechanismListButton extends javax.swing.JPanel {

    /** Creates new form MechanismListButton */
    public MechanismListButton() {
        initComponents ();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        frameListButton = new react.reactions.FrameListButton();
        setLayout(new java.awt.GridLayout(1, 1));
        
        
        add(frameListButton);
        
    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private react.reactions.FrameListButton frameListButton;
    // End of variables declaration//GEN-END:variables

}
