/*
 * ReactMechanismObjectPanel.java
 *
 * Created on January 21, 2002, 8:05 AM
 */

package react.mechanisms;
import javax.swing.JPanel;
import javax.swing.JFrame;
/**
 *
 * @author  reaction
 * @version 
 */
public class ReactMechanismObjectPanel extends javax.swing.JPanel {
    public ReactMechanismGraphNode nodeInfo;
    
    /** Creates new form ReactMechanismObjectPanel */
    public ReactMechanismObjectPanel(ReactMechanismGraphNode info) {
        initComponents ();
        nodeInfo = info;
        viewObject.setText(nodeInfo.nodeName);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        viewObject = new javax.swing.JButton();
        setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints1;
        
        viewObject.setToolTipText("Press to view Object");
        viewObject.setText("Object");
        viewObject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewObjectMouseClicked(evt);
            }
        }
        );
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        add(viewObject, gridBagConstraints1);
        
    }//GEN-END:initComponents

  private void viewObjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewObjectMouseClicked
// Add your handling code here:
      JPanel pnl = nodeInfo.objectAsPanel();
      JFrame fr  = new JFrame(nodeInfo.nodeName);
      fr.getContentPane().add(pnl);
      fr.setVisible(true);
      fr.pack();
      fr.show();
  }//GEN-LAST:event_viewObjectMouseClicked


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton viewObject;
  // End of variables declaration//GEN-END:variables

}
