/*
 * ReactMechanismGenerationStep.java
 *
 * Created on January 22, 2001, 1:34 PM
 */

package react.mechanisms;
import react.utilities.*;
import java.util.StringTokenizer;
import javax.swing.*;

/**
 *
 * @author  reaction
 * @version 
 */
public class ReactMechanismGenerationStepMenu extends javax.swing.JPanel {

    ReactMechanismGenerationStep Step;
    
    /** Creates new form ReactMechanismGenerationStep */
    public ReactMechanismGenerationStepMenu() {
        initComponents ();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        StepLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        molPanel = new react.utilities.StandardListPanel();
        stepPanel = new react.utilities.StandardListPanel();
        setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints1;
        
        jPanel1.setLayout(new java.awt.GridLayout(1, 2));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 30));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 40));
        
        jButton1.setPreferredSize(new java.awt.Dimension(200, 30));
          jButton1.setText("Mechanism Step: ");
          jPanel1.add(jButton1);
          
          
        StepLabel.setPreferredSize(new java.awt.Dimension(200, 30));
          StepLabel.setText(new String(StepName));
          jPanel1.add(StepLabel);
          
          
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridwidth = 0;
        add(jPanel1, gridBagConstraints1);
        
        
        jPanel2.setLayout(new java.awt.GridLayout(1, 2));
        
        molPanel.setPreferredSize(new java.awt.Dimension(200, 200));
          molPanel.setMinimumSize(new java.awt.Dimension(200, 200));
          molPanel.setToolTipText("Step Molecules");
          molPanel.setMaximumSize(new java.awt.Dimension(200, 200));
          jPanel2.add(molPanel);
          
          
        stepPanel.setPreferredSize(new java.awt.Dimension(200, 200));
          stepPanel.setMinimumSize(new java.awt.Dimension(200, 200));
          stepPanel.setToolTipText("Step Reaction Patterns");
          jPanel2.add(stepPanel);
          
          
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        add(jPanel2, gridBagConstraints1);
        
    }//GEN-END:initComponents

    public void setData(ReactMechanismGenerationStep step) {
        String[] mols = step.stepMolecules;
        String[] pats = step.Patterns;
        try {
            molPanel.setData(mols);
            } catch (NullPointerException nx) {
        System.out.println("No Molecules"); }
        try {
            stepPanel.setData(pats);
        } catch(NullPointerException ny) {
            System.out.println("No Patterns");
        }
    }
    public void setNumber(int stepnumber) {
        Integer i = new Integer(stepnumber);
        StepName = i.toString();
        StepNumber = stepnumber;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel StepLabel;
    private javax.swing.JPanel jPanel2;
    public react.utilities.StandardListPanel molPanel;
    public react.utilities.StandardListPanel stepPanel;
    // End of variables declaration//GEN-END:variables

    public int StepNumber = 0;    

    public String StepName = new String("Step");
    
    public int numElements = 0;
    
    public int numMolecules = 0;
    
}
