/*
 * ReactMechanismGraphOptions.java
 *
 * Created on January 20, 2002, 3:25 PM
 */

package react.mechanisms;

/**
 *
 * @author  reaction
 * @version 
 */
public class ReactMechanismGraphOptions extends javax.swing.JPanel {
    ReactionMechanismGraphMenu mechGraph;
    /** Creates new form ReactMechanismGraphOptions */
    public ReactMechanismGraphOptions(ReactionMechanismGraphMenu grph) {
        initComponents ();
        mechGraph = grph;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        mechWithReactions = new javax.swing.JRadioButton();
        mechWithRxnClasses = new javax.swing.JRadioButton();
        setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints1;
        
        
        mechWithReactions.setToolTipText("Graph Mechanism With Reactions");
          mechWithReactions.setText("Reactions");
          mechWithReactions.addMouseListener(new java.awt.event.MouseAdapter() {
              public void mouseClicked(java.awt.event.MouseEvent evt) {
                  mechWithReactionsMouseClicked(evt);
              }
          }
          );
          jPanel1.add(mechWithReactions);
          
          
        mechWithRxnClasses.setToolTipText("Graph Reaction Classes");
          mechWithRxnClasses.setLabel("Reaction Classes");
          mechWithRxnClasses.setSelected(true);
          mechWithRxnClasses.addMouseListener(new java.awt.event.MouseAdapter() {
              public void mouseClicked(java.awt.event.MouseEvent evt) {
                  mechWithRxnClassesMouseClicked(evt);
              }
          }
          );
          jPanel1.add(mechWithRxnClasses);
          
          
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        add(jPanel1, gridBagConstraints1);
        
    }//GEN-END:initComponents

  private void mechWithReactionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mechWithReactionsMouseClicked
  }//GEN-LAST:event_mechWithReactionsMouseClicked

  private void mechWithRxnClassesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mechWithRxnClassesMouseClicked
  }//GEN-LAST:event_mechWithRxnClassesMouseClicked

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel jPanel1;
  private javax.swing.JRadioButton mechWithReactions;
  public javax.swing.JRadioButton mechWithRxnClasses;
  // End of variables declaration//GEN-END:variables

}
