/*
 * KeyWordPanel.java
 *
 * Created on July 19, 2006, 9:52 AM
 */

package blurock.coreobjects;

import javax.swing.table.DefaultTableModel;
import blurock.coreobjects.BaseDataKeyWords;
/**
 *
 * @author  reaction
 */
public class KeyWordPanel extends javax.swing.JPanel {
    
    /** Creates new form KeyWordPanel */
    public KeyWordPanel() {
        initComponents();
    }
    public KeyWordPanel(BaseDataKeyWords keys) {
        initComponents();
        String[] keysS = keys.keyWordAsStringArray();
        insertKeys(keysS);
    }
    public KeyWordPanel(String[] keysS) {
        initComponents();
        insertKeys(keysS);       
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        tableScrollPane = new javax.swing.JScrollPane();
        keyWordTable = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        setMinimumSize(new java.awt.Dimension(453, 403));
        tableScrollPane.setMinimumSize(new java.awt.Dimension(200, 400));
        keyWordTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Include", "Species"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableScrollPane.setViewportView(keyWordTable);

        add(tableScrollPane, java.awt.BorderLayout.CENTER);

    }
    // </editor-fold>//GEN-END:initComponents
    public void insertKeys(String[] keysS) {
        clearTable();
        DefaultTableModel model = (DefaultTableModel) keyWordTable.getModel();
        for(int i=0;i<keysS.length;i++) {
            Object[] row = new Object[2];
            row[0] = new Boolean(true); 
            row[1] = keysS[i];
            model.addRow(row);
        }
    }
    public void clearTable() {
        DefaultTableModel model = (DefaultTableModel) keyWordTable.getModel();
        int n = model.getRowCount();
        for(int i=n; i>0;i--) {
            model.removeRow(i-1);
        }
    }
    public String[] getSelectedKeys() {
        
        DefaultTableModel model = (DefaultTableModel) keyWordTable.getModel();
        int n = model.getRowCount();
        String[] keys = new String[n];
        int selectedcount = 0;
        System.out.println("=====================================================================================================================");
        for(int i=0; i<n;i++) {
            Boolean selected = (Boolean) model.getValueAt(i, 0);
            System.out.println((String) model.getValueAt(i, 1) + " Selected: " + selected.toString());
            if(selected.booleanValue() == Boolean.TRUE) {
                keys[selectedcount++] = (String) model.getValueAt(i, 1);
            }
        }
        String[] ans = new String[selectedcount];
        for(int i=0;i<selectedcount;i++) {
            ans[i] = keys[i];
        }
         System.out.println("=====================================================================================================================");
       return ans;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable keyWordTable;
    private javax.swing.JScrollPane tableScrollPane;
    // End of variables declaration//GEN-END:variables
    
}
