/*
 * ExternalInfoPanel.java
 *
 * Created on June 26, 2001, 10:43 AM
 */

package xml.structure;
import react.utilities.*;
/**
 *
 * @author  reaction
 * @version 
 */
public class ExternalInfoPanel extends javax.swing.JPanel {

    String envTitle = "Dependent Environments";
    String modTitle = "Dependent Modules";
    BaseDataExternalInfo extInfo;
    
    int maxSize = 20;
    
    String[] possibleEnvironments = {"CoreObjects"};
    String[] possibleModules     = {"CoreDataObjects",
                                    "LogicalObjects",
                                    "NumericObjects"};
    /** Creates new form ExternalInfoPanel */
    public ExternalInfoPanel(BaseDataExternalInfo info) {
        extInfo = info;
        initComponents ();
        environmentList.addNewItems(extInfo.environmentNames);
        moduleList.addNewItems(extInfo.moduleNames);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        environmentList = new SimpleManageListItems(envTitle,possibleEnvironments,maxSize);
        
        jPanel2 = new javax.swing.JPanel();
        moduleList = new SimpleManageListItems(modTitle,possibleModules,maxSize);
        setLayout(new java.awt.GridLayout(1, 2));
        
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
        }
        );
        
        java.awt.GridBagConstraints gridBagConstraints3;
          jPanel1.add(environmentList);
          
          
        add(jPanel1);
        
        
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel2MouseExited(evt);
            }
        }
        );
        
        java.awt.GridBagConstraints gridBagConstraints4;
          jPanel2.add(moduleList);
          
          
        add(jPanel2);
        
    }//GEN-END:initComponents

  private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
// Add your handling code here:
      update();
  }//GEN-LAST:event_jPanel2MouseClicked

  private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
// Add your handling code here:
      update();
  }//GEN-LAST:event_jPanel1MouseClicked

  private void jPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseExited
// Add your handling code here:
      update();
  }//GEN-LAST:event_jPanel2MouseExited

  private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited
// Add your handling code here:
      update();
  }//GEN-LAST:event_jPanel1MouseExited
    void update() {
        System.out.println("External Updated");
        extInfo.setEnvironmentList(environmentList.getElements());
        extInfo.setModuleList(moduleList.getElements());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private react.utilities.SimpleManageListItems environmentList;
    private javax.swing.JPanel jPanel2;
    private react.utilities.SimpleManageListItems moduleList;
    // End of variables declaration//GEN-END:variables

}
