/*
 * ReactionSetupScripts.java
 *
 * Created on February 10, 2001, 4:15 PM
 */

package react.common;

/**
 *
 * @author  reaction
 * @version 
 */
public class ReactionSetupScripts extends javax.swing.JPanel {

    /** Creates new form ReactionSetupScripts */
    public ReactionSetupScripts() {
        initComponents ();
        moleculeSetup.setDefaultValue("MoleculeSetup.sh");
        moleculeSetup.setValueName("Setup Molecule definitions and classes");
        reactionSetup.setDefaultValue("ReactionSetup.sh");
        reactionSetup.setValueName("Setup Reaction definitions and classes");
        mechanismSetup.setDefaultValue("MechanismSetup.sh");
        mechanismSetup.setValueName("Setup Mechanism definitions and classes");
        moleculeScriptDirectory.setDefaultValue("/usr/local/Software/Reaction/data/mol/scripts/");
        moleculeScriptDirectory.setValueName("Molecule Directory");
        reactionScriptDirectory.setDefaultValue("/usr/local/Software/Reaction/data/rxn/scripts/");
        reactionScriptDirectory.setValueName("Reaction Directory");
        mechanismScriptDirectory.setDefaultValue("/usr/local/Software/Reaction/data/mech/scripts/");
        mechanismScriptDirectory.setValueName("Mechanism Directory");
        standardMechanismSetup.setDefaultValue("StandardMechanismSetup.sh");
        standardMechanismSetup.setValueName("Standard Mechanism Setup");
     }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
     private void initComponents() {//GEN-BEGIN:initComponents
         jTabbedPane1 = new javax.swing.JTabbedPane();
         moleculePanel = new javax.swing.JPanel();
         moleculeScriptDirectory = new react.common.StandardName();
         moleculeSetup = new react.common.StandardName();
         reactionPanel = new javax.swing.JPanel();
         reactionScriptDirectory = new react.common.StandardName();
         reactionSetup = new react.common.StandardName();
         mechanismPanel = new javax.swing.JPanel();
         mechanismScriptDirectory = new react.common.StandardName();
         mechanismSetup = new react.common.StandardName();
         standardMechanismSetup = new react.common.StandardName();
         setLayout(new java.awt.BorderLayout());
         
         
         moleculePanel.setLayout(new java.awt.GridLayout(5, 1));
           
           moleculeScriptDirectory.setLayout(new java.awt.GridLayout(2, 3));
             moleculePanel.add(moleculeScriptDirectory);
             
             
           moleculeSetup.setLayout(new java.awt.GridLayout(2, 3));
             moleculeSetup.setName("readBasicMolecules");
             moleculeSetup.setToolTipText("Setup molecule definitions and classes");
             moleculePanel.add(moleculeSetup);
             
             jTabbedPane1.addTab("Molecules", null, moleculePanel, "The setup scripts of the molecules");
           
           
         reactionPanel.setLayout(new java.awt.GridLayout(5, 1));
           
           reactionScriptDirectory.setLayout(new java.awt.GridLayout(2, 3));
             reactionPanel.add(reactionScriptDirectory);
             
             
           reactionSetup.setLayout(new java.awt.GridLayout(2, 3));
             reactionSetup.setToolTipText("Setup mechanism definitions and classes");
             reactionPanel.add(reactionSetup);
             
             jTabbedPane1.addTab("Reactions", null, reactionPanel, "Reaction setup scripts");
           
           
         mechanismPanel.setLayout(new java.awt.GridLayout(5, 1));
           
           mechanismScriptDirectory.setLayout(new java.awt.GridLayout(2, 3));
             mechanismPanel.add(mechanismScriptDirectory);
             
             
           mechanismSetup.setLayout(new java.awt.GridLayout(2, 3));
             mechanismSetup.setToolTipText("Setup molecule definitions and classes");
             mechanismPanel.add(mechanismSetup);
             
             
           standardMechanismSetup.setLayout(new java.awt.GridLayout(2, 3));
             mechanismPanel.add(standardMechanismSetup);
             
             jTabbedPane1.addTab("Mechanisms", null, mechanismPanel, "Mechanism setup scripts");
           
           
         add(jTabbedPane1, java.awt.BorderLayout.CENTER);
         
     }//GEN-END:initComponents


     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JTabbedPane jTabbedPane1;
     private javax.swing.JPanel moleculePanel;
     public react.common.StandardName moleculeScriptDirectory;
     public react.common.StandardName moleculeSetup;
     private javax.swing.JPanel reactionPanel;
     public react.common.StandardName reactionScriptDirectory;
     public react.common.StandardName reactionSetup;
     private javax.swing.JPanel mechanismPanel;
     public react.common.StandardName mechanismScriptDirectory;
     public react.common.StandardName mechanismSetup;
     public react.common.StandardName standardMechanismSetup;
     // End of variables declaration//GEN-END:variables

}
