/*
 * ReactionScripts.java
 *
 * Created on January 20, 2001, 12:48 PM
 */

package react.common;

/**
 *
 * @author  reaction
 * @version 
 */
public class ReactionScripts extends javax.swing.JFrame {
    public String rootdir;
    /** Creates new form ReactionScripts */
    public ReactionScripts(String d) {
        initComponents ();
        rootdir = d;
//        String rootdir = "/home/reaction/cvs/react/programs/scripts/";
        rootdir = d + "/programs/scripts/";
//        String rootdir = "/x2/webservices/react/programs/scripts/";
        listMolecules.setDefaultValue(rootdir + "printmols.sh");
        listMolecules.setValueName("List Molecule Names");
        listReactions.setDefaultValue(rootdir + "printrxns.sh");
        listReactions.setValueName("List Reaction Names");
        listMechanisms.setDefaultValue(rootdir + "printmechs.sh");
        listMechanisms.setValueName("List Mechanism Names");
        listSubstructures.setDefaultValue(rootdir + "printsubs.sh");
        listSubstructures.setValueName("List Substructure Names");
        listReactionPatterns.setDefaultValue(rootdir + "printrxnpats.sh");
        listReactionPatterns.setValueName("List Rxn Pat Names");

        printMolecule.setDefaultValue(rootdir + "printmolecule.sh");
        printMolecule.setValueName("Print Molecule");
        printReaction.setDefaultValue(rootdir + "printrxn.sh");
        printReaction.setValueName("Print Reaction");
        printMechanism.setDefaultValue(rootdir + "printmechs.sh");
        printMechanism.setValueName("Print Mechanism");
        printSubstructure.setDefaultValue(rootdir + "printsubstructure.sh");
        printSubstructure.setValueName("Print Substructure");
        printReactionPattern.setDefaultValue(rootdir + "printrxnpat.sh");
        printReactionPattern.setValueName("Print Rxn Pat");

        runCombineMechanism.setDefaultValue(rootdir + "combinemech.sh");
        runCombineMechanism.setValueName("Combine Mechanisms");
        runChain.setDefaultValue(rootdir + "runchain.sh");
        runChain.setValueName("Generate Mechanism");
        printOutMechanism.setDefaultValue(rootdir + "printoutmech.sh");
        printOutMechanism.setValueName("Print Out Mechanism");
        thermoFromMolecule.setDefaultValue(rootdir + "thermofrommolecules.sh");
        thermoFromMolecule.setValueName("Thermodynamics From Molecules");
        chemkinFromBenson.setDefaultValue(rootdir + "benson2chemkin.sh");
        chemkinFromBenson.setValueName("Convert Benson Property to Chemkin");
       
        pack ();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Molecules = new javax.swing.JPanel();
        listMolecules = new react.common.StandardName();
        printMolecule = new react.common.StandardName();
        thermoFromMolecule = new react.common.StandardName();
        chemkinFromBenson = new react.common.StandardName();
        Reactions = new javax.swing.JPanel();
        listReactions = new react.common.StandardName();
        printReaction = new react.common.StandardName();
        Mechanisms = new javax.swing.JPanel();
        listMechanisms = new react.common.StandardName();
        printMechanism = new react.common.StandardName();
        runCombineMechanism = new react.common.StandardName();
        runChain = new react.common.StandardName();
        printOutMechanism = new react.common.StandardName();
        Substructures = new javax.swing.JPanel();
        listSubstructures = new react.common.StandardName();
        printSubstructure = new react.common.StandardName();
        RxnPats = new javax.swing.JPanel();
        listReactionPatterns = new react.common.StandardName();
        printReactionPattern = new react.common.StandardName();

        setTitle("ReactionScripts");
        setName("ReactionScripts");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        Molecules.setLayout(new java.awt.GridLayout(5, 1));

        Molecules.setPreferredSize(new java.awt.Dimension(300, 200));
        Molecules.add(listMolecules);

        Molecules.add(printMolecule);

        thermoFromMolecule.setFont(new java.awt.Font("Dialog", 0, 11));
        thermoFromMolecule.setMinimumSize(new java.awt.Dimension(8, 18));
        Molecules.add(thermoFromMolecule);

        chemkinFromBenson.setFont(new java.awt.Font("Dialog", 0, 11));
        chemkinFromBenson.setMinimumSize(new java.awt.Dimension(8, 18));
        Molecules.add(chemkinFromBenson);

        jTabbedPane1.addTab("Molecule", null, Molecules, "");

        Reactions.setLayout(new java.awt.GridLayout(5, 1));

        Reactions.add(listReactions);

        Reactions.add(printReaction);

        jTabbedPane1.addTab("Reaction", null, Reactions, "");

        Mechanisms.setLayout(new java.awt.GridLayout(5, 1));

        Mechanisms.add(listMechanisms);

        Mechanisms.add(printMechanism);

        Mechanisms.add(runCombineMechanism);

        Mechanisms.add(runChain);

        Mechanisms.add(printOutMechanism);

        jTabbedPane1.addTab("Mechanism", null, Mechanisms, "");

        Substructures.setLayout(new java.awt.GridLayout(5, 1));

        listSubstructures.setLayout(new java.awt.GridLayout(1, 1));

        Substructures.add(listSubstructures);

        printSubstructure.setLayout(new java.awt.GridLayout(1, 1));

        Substructures.add(printSubstructure);

        jTabbedPane1.addTab("Substructures", null, Substructures, "");

        RxnPats.setLayout(new java.awt.GridLayout(5, 1));

        listReactionPatterns.setLayout(new java.awt.GridLayout(1, 1));

        RxnPats.add(listReactionPatterns);

        printReactionPattern.setLayout(new java.awt.GridLayout(1, 1));

        RxnPats.add(printReactionPattern);

        jTabbedPane1.addTab("RxnPats", null, RxnPats, "");

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit (0);
    }//GEN-LAST:event_exitForm

    /**
    * @param args the command line arguments
    */
    public static void main (String args[]) {
        new ReactionScripts (args[0]).show ();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel RxnPats;
    public javax.swing.JPanel Reactions;
    public react.common.StandardName printReaction;
    public react.common.StandardName printMechanism;
    public react.common.StandardName listReactions;
    public react.common.StandardName listReactionPatterns;
    public javax.swing.JPanel Mechanisms;
    public react.common.StandardName printSubstructure;
    public react.common.StandardName runChain;
    private javax.swing.JPanel Substructures;
    public javax.swing.JPanel Molecules;
    public react.common.StandardName listSubstructures;
    public react.common.StandardName listMolecules;
    public react.common.StandardName runCombineMechanism;
    public react.common.StandardName printMolecule;
    public react.common.StandardName chemkinFromBenson;
    public react.common.StandardName thermoFromMolecule;
    public react.common.StandardName printOutMechanism;
    public react.common.StandardName printReactionPattern;
    public react.common.StandardName listMechanisms;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

}
