/*
 * StandardName.java
 *
 * Created on January 20, 2001, 11:19 AM
 */

package react.common;

/**
 *
 * @author  reaction
 * @version 
 */
public class StandardValue extends javax.swing.JPanel {

    /** Creates new form StandardName */
    public StandardValue() {
        initComponents ();
        setDefaultValue(0);
        setValueName("Name");
    }

    public StandardValue(java.lang.String name,int defaultValue) {
        initComponents();
        setDefaultValue(defaultValue);
        setValueName(name);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        setLayout(new java.awt.GridLayout(1, 2));
        setPreferredSize(new java.awt.Dimension(120, 20));
        
        jLabel1.setText("jLabel1");
        
        add(jLabel1);
        
        
        jTextField1.setPreferredSize(new java.awt.Dimension(69, 20));
        jTextField1.setText("jTextField1");
        
        add(jTextField1);
        
    }//GEN-END:initComponents

    public void setDefaultValue(int value) {
        Integer v = new Integer(value);
        jTextField1.setText(v.toString());
    }    

    public void setValueName(java.lang.String name) {
        jLabel1.setText(name);
    }
    
    public int getValue() {
        String n = jTextField1.getText();
        Integer i = new Integer(n);
        return i.intValue();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
