/*
 * ThermoNASAPolyPanel.java
 *
 * Created on August 21, 2006, 3:42 PM
 */

package react.mechanisms.chemkin;

import java.util.StringTokenizer;
import javax.swing.table.DefaultTableModel;
import java.io.IOException;
import utilities.ErrorFrame;

/**
 *
 * @author  reaction
 */
public class ThermoNASAPolyPanel extends javax.swing.JPanel {
   public ThermoNASAPoly NASA;
    /** Creates new form ThermoNASAPolyPanel */
    public ThermoNASAPolyPanel() {
        initComponents();
    }
    public ThermoNASAPolyPanel(String fullname, ThermoNASAPoly nasa) {
        initComponents();
        fullMolNameText.setText(fullname);
        NASA = nasa;
        setWithNASA(NASA);
    }    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        thermoDataPanel = new javax.swing.JPanel();
        thermoData = new javax.swing.JPanel();
        fullNameLabel = new javax.swing.JLabel();
        fullMolNameText = new javax.swing.JTextField();
        chemkinNameLabel = new javax.swing.JLabel();
        chemkinNameText = new javax.swing.JTextField();
        formulaLabel = new javax.swing.JLabel();
        formulaText = new javax.swing.JTextField();
        lowerTLabel = new javax.swing.JLabel();
        lowerTText = new javax.swing.JTextField();
        commonTLabel = new javax.swing.JLabel();
        commonTText = new javax.swing.JTextField();
        upperTLabel = new javax.swing.JLabel();
        upperTText = new javax.swing.JTextField();
        thermCoefficients = new javax.swing.JTable();
        transferDataButton = new javax.swing.JButton();
        nasaPolynomialPanel = new javax.swing.JPanel();
        nasaPolynomialTest = new javax.swing.JTextArea();
        readNASATextButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        thermoDataPanel.setLayout(new java.awt.BorderLayout());

        thermoData.setLayout(new java.awt.GridLayout(7, 2));

        fullNameLabel.setText("Molecule Full Name");
        thermoData.add(fullNameLabel);

        fullMolNameText.setText("molecule");
        thermoData.add(fullMolNameText);

        chemkinNameLabel.setText("CHEMKIN Name");
        thermoData.add(chemkinNameLabel);

        chemkinNameText.setText("M");
        thermoData.add(chemkinNameText);

        formulaLabel.setText("Formula");
        thermoData.add(formulaLabel);

        formulaText.setText("M1");
        thermoData.add(formulaText);

        lowerTLabel.setText("Lower Temperature");
        thermoData.add(lowerTLabel);

        lowerTText.setText("300.0");
        thermoData.add(lowerTText);

        commonTLabel.setText("Common Temperature");
        thermoData.add(commonTLabel);

        commonTText.setText("1000.0");
        thermoData.add(commonTText);

        upperTLabel.setText("Upper Temperature");
        thermoData.add(upperTLabel);

        upperTText.setText("3000.0");
        thermoData.add(upperTText);

        thermoDataPanel.add(thermoData, java.awt.BorderLayout.CENTER);

        jPanel1.add(thermoDataPanel, java.awt.BorderLayout.NORTH);

        thermCoefficients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"a1", new Double(0.0), new Double(0.0)},
                {"a2", new Double(0.0), new Double(0.0)},
                {"a3", new Double(0.0), new Double(0.0)},
                {"a4", new Double(0.0), new Double(0.0)},
                {"a5", new Double(0.0), new Double(0.0)},
                {"a6", new Double(0.0), new Double(0.0)},
                {"a7", new Double(0.0), new Double(0.0)}
            },
            new String [] {
                "Coefficient", "High Temperature", "Low Temperature"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        thermCoefficients.setTableHeader(null);
        jPanel1.add(thermCoefficients, java.awt.BorderLayout.CENTER);

        transferDataButton.setText("Transfer Thermo Data");
        transferDataButton.setToolTipText("Transfers the thermodynamic data from above fields");
        transferDataButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transferDataButtonMouseClicked(evt);
            }
        });

        jPanel1.add(transferDataButton, java.awt.BorderLayout.SOUTH);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        nasaPolynomialPanel.setLayout(new java.awt.BorderLayout());

        nasaPolynomialPanel.setBorder(new javax.swing.border.TitledBorder("NASA Polynomial Text"));
        nasaPolynomialTest.setFont(new java.awt.Font("Courier", 0, 14));
        nasaPolynomialTest.setMinimumSize(new java.awt.Dimension(200, 100));
        nasaPolynomialTest.setPreferredSize(new java.awt.Dimension(200, 100));
        nasaPolynomialPanel.add(nasaPolynomialTest, java.awt.BorderLayout.CENTER);

        readNASATextButton.setText("Read NASA Polynomial Text");
        readNASATextButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                readNASATextButtonMouseClicked(evt);
            }
        });

        nasaPolynomialPanel.add(readNASATextButton, java.awt.BorderLayout.SOUTH);

        add(nasaPolynomialPanel, java.awt.BorderLayout.SOUTH);

    }
    // </editor-fold>//GEN-END:initComponents

    private void transferDataButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferDataButtonMouseClicked
        setFieldsToNASA();
    }//GEN-LAST:event_transferDataButtonMouseClicked
    public void setFieldsToNASA() {
        DefaultTableModel model = (DefaultTableModel) thermCoefficients.getModel();
        try {
        NASA = new ThermoNASAPoly();
        NASA.name = chemkinNameText.getText();
        Double lowerD = new Double(lowerTText.getText());
        Double upperD = new Double(upperTText.getText());
        Double commonD = new Double(commonTText.getText());
        NASA.lowerT = lowerD.doubleValue();
        NASA.upperT = upperD.doubleValue();
        NASA.middleT = commonD.doubleValue();
        for(int i=0;i<6;i++) {
            Double lower = (Double) model.getValueAt(i,2);
            Double upper = (Double) model.getValueAt(i,1);
            NASA.lower[i] = lower.doubleValue();
            NASA.upper[i] = upper.doubleValue();
        }
        NASA.extractFormulaFromText(formulaText.getText());
        nasaPolynomialTest.setText(NASA.toString());
        } catch(NumberFormatException ex) {
            ErrorFrame fr = new ErrorFrame("Numeric Field not a number");
            fr.setVisible(true);
        } catch(IOException ex) {
            ErrorFrame fr = new ErrorFrame(ex.toString());
            fr.setVisible(true);
        }
    }
    private void readNASATextButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readNASATextButtonMouseClicked
        try {
            readNASAPolynomial();
        } catch(IOException ex) {
            ErrorFrame fr = new ErrorFrame("Error in reading NASA Polynomial from Text:\n" + ex.toString());
            fr.setVisible(true);
        }
    }//GEN-LAST:event_readNASATextButtonMouseClicked
    public void setWithNASA(ThermoNASAPoly nasa) {
        DefaultTableModel model = (DefaultTableModel) thermCoefficients.getModel();
        chemkinNameText.setText(nasa.name);
        formulaText.setText(nasa.moleculeFormula());
        Double lowerD = new Double(nasa.lowerT);
        Double upperD = new Double(nasa.upperT);
        Double commonD = new Double(nasa.middleT);
        lowerTText.setText(lowerD.toString());
        upperTText.setText(upperD.toString());
        commonTText.setText(commonD.toString());
        for(int i=0;i<6;i++) {
            Double hi = new Double(nasa.upper[i]);
            Double lo = new Double(nasa.lower[i]);
            model.setValueAt(hi, i, 1);
            model.setValueAt(lo,i, 2);
        }
    }
    public void readNASAPolynomial() throws IOException {
        StringTokenizer tok = new StringTokenizer(nasaPolynomialTest.getText(),"\n");
        if(tok.countTokens() >= 4) {
            NASA = new ThermoNASAPoly();
            String l1 = tok.nextToken();
            String l2 = tok.nextToken();
            String l3 = tok.nextToken();
            String l4 = tok.nextToken();
            NASA.parse(l1,l2,l3,l4);
            setWithNASA(NASA);
        } else {
            throw new IOException("Incomplete NASA polynomial");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chemkinNameLabel;
    private javax.swing.JTextField chemkinNameText;
    private javax.swing.JLabel commonTLabel;
    private javax.swing.JTextField commonTText;
    private javax.swing.JLabel formulaLabel;
    private javax.swing.JTextField formulaText;
    protected javax.swing.JTextField fullMolNameText;
    private javax.swing.JLabel fullNameLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lowerTLabel;
    private javax.swing.JTextField lowerTText;
    private javax.swing.JPanel nasaPolynomialPanel;
    private javax.swing.JTextArea nasaPolynomialTest;
    private javax.swing.JButton readNASATextButton;
    private javax.swing.JTable thermCoefficients;
    private javax.swing.JPanel thermoData;
    private javax.swing.JPanel thermoDataPanel;
    private javax.swing.JButton transferDataButton;
    private javax.swing.JLabel upperTLabel;
    private javax.swing.JTextField upperTText;
    // End of variables declaration//GEN-END:variables
    
}
