/*
 * ReadClassInstAttr.java
 *
 * Created on February 15, 2001, 2:51 PM
 */

package blurock.instattr;
import blurock.core.*;
import blurock.utilities.*;
import react.common.TopReactionMenu;
import utilities.OutputFrame;

import javax.swing.JTextArea;
import javax.swing.JFileChooser;
import java.io.File;

/**
 *
 * @author  reaction
 * @version 
 */
public class ReadClassInstAttr extends javax.swing.JPanel {

    TopReactionMenu Top;
    
    /** Creates new form ReadClassInstAttr */
    public ReadClassInstAttr(TopReactionMenu top) {
        Top = top;
        initComponents ();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        dirLabel = new javax.swing.JLabel();
        defaultDirectory = new javax.swing.JTextField();
        rootNameButton = new javax.swing.JButton();
        rootName = new javax.swing.JTextField();
        classFileNameButton = new javax.swing.JButton();
        classFileName = new javax.swing.JTextField();
        attrFileNameButton = new javax.swing.JButton();
        attrFileName = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        readFiles = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(4, 2));

        jPanel1.setBorder(new javax.swing.border.TitledBorder("Setup"));
        dirLabel.setText("Directory");
        jPanel1.add(dirLabel);

        defaultDirectory.setText("./");
        jPanel1.add(defaultDirectory);

        rootNameButton.setToolTipText("Click to set files to standard names");
        rootNameButton.setText("Root Name");
        rootNameButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rootNameButtonMouseClicked(evt);
            }
        });

        jPanel1.add(rootNameButton);

        rootName.setText("Test");
        jPanel1.add(rootName);

        classFileNameButton.setToolTipText("Click to browse for class file");
        classFileNameButton.setText("Class File");
        classFileNameButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                classFileNameButtonMouseClicked(evt);
            }
        });

        jPanel1.add(classFileNameButton);

        classFileName.setText("TestClass.inp");
        jPanel1.add(classFileName);

        attrFileNameButton.setToolTipText("Click to browse for Attribute File");
        attrFileNameButton.setText("Attribute File");
        attrFileNameButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attrFileNameButtonMouseClicked(evt);
            }
        });

        jPanel1.add(attrFileNameButton);

        attrFileName.setToolTipText("Attribute file to read");
        attrFileName.setText("Test.inp");
        jPanel1.add(attrFileName);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout());

        jPanel2.setBorder(new javax.swing.border.TitledBorder("Read"));
        readFiles.setToolTipText("Read in both attribute and class files");
        readFiles.setText("Read Files");
        readFiles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                readFilesMouseClicked(evt);
            }
        });

        jPanel2.add(readFiles);

        add(jPanel2, java.awt.BorderLayout.SOUTH);

    }//GEN-END:initComponents

  private void attrFileNameButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attrFileNameButtonMouseClicked
// Add your handling code here:
      String name = getAttrFile();
      attrFileName.setText(name);
  }//GEN-LAST:event_attrFileNameButtonMouseClicked

  private void classFileNameButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_classFileNameButtonMouseClicked
// Add your handling code here:
      String name = getClassFile();
      classFileName.setText(name);
  }//GEN-LAST:event_classFileNameButtonMouseClicked

  private void readFilesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readFilesMouseClicked
// Add your handling code here:
      readData();
  }//GEN-LAST:event_readFilesMouseClicked

  private void rootNameButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rootNameButtonMouseClicked
// Add your handling code here:
      String rname = rootName.getText();
      classFileName.setText(rname+ "Class.inp");
      attrFileName.setText(rname+".inp");
  }//GEN-LAST:event_rootNameButtonMouseClicked

  private String getClassFile()
    {
	JFileChooser f = new JFileChooser(defaultDirectory.getText());
	StandardClassFileFilter classfiles = new StandardClassFileFilter();
	f.addChoosableFileFilter(classfiles);
	f.setFileFilter(classfiles);
	f.showOpenDialog(Top);
	File chosen  = f.getSelectedFile();
	return chosen.getPath();
    }
  private String getAttrFile()
    {
	JFileChooser f = new JFileChooser(defaultDirectory.getText());
	StandardAttrFileFilter classfiles = new StandardAttrFileFilter();
	f.addChoosableFileFilter(classfiles);
	f.setFileFilter(classfiles);
	f.showOpenDialog(Top);
	File chosen  = f.getSelectedFile();
	return chosen.getPath();
    }
    
  private void readData()
    {
        ReadFile rd = new ReadFile(Top,classFileName.getText(),
                            attrFileName.getText(),true);
        OutputFrame fr = new OutputFrame(rd.commandOutput);
        fr.show();
	updateUI();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField attrFileName;
    private javax.swing.JButton attrFileNameButton;
    private javax.swing.JTextField classFileName;
    private javax.swing.JButton classFileNameButton;
    private javax.swing.JTextField defaultDirectory;
    private javax.swing.JLabel dirLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton readFiles;
    private javax.swing.JTextField rootName;
    private javax.swing.JButton rootNameButton;
    // End of variables declaration//GEN-END:variables

}
